server:
  port: 8082
spring:
  application:
    name: product
  data:
    mongodb:
#      url: mongodb://127.0.0.1:27017/?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
      database: monicode
      port: 27017
      host: localhost
#      authentication-database: admin
#      username: rootuser
#      password: rootpass
#      socketTimeout: 20000


      #      url: mongodb://localhost:27017@monicode?authSource=admin
#mongodb://127.0.0.1:27017/?authSource=admin&compressors=disabled&gssapiServiceName=mongodb:

#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/customer
#    username: monicode
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true
#  zipkin:
#    base-url: http://localhost:9411
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true